class UserModel {
  final int? id; // Unique identifier for the user (optional, typically auto-generated by a database).
  final String name; // User's name.
  final String phone; // User's phone number, used as a unique identifier for the user.
  final String email; // User's email address.
  final String password; // User's password. (In production, it should be stored as a hashed password for security reasons).
  final String profileImagePath; // Path or base64 encoded string representing the user's profile image.

  // Constructor to initialize the UserModel object with required parameters.
  UserModel({
    this.id, // Optional parameter for the user's ID.
    required this.name, // Required parameter for the user's name.
    required this.phone, // Required parameter for the user's phone number.
    required this.email, // Required parameter for the user's email.
    required this.password, // Required parameter for the user's password.
    required this.profileImagePath, // Required parameter for the user's profile image path.
  });

  // Factory constructor to convert a Map (e.g., from Firestore or SQLite) to a UserModel object.
  factory UserModel.fromMap(Map<String, dynamic> map) {
    return UserModel(
      id: map['id'], // Extract the 'id' from the map (can be null if it's not set).
      name: map['name'], // Extract the 'name' from the map.
      phone: map['phone'], // Extract the 'phone' from the map.
      email: map['email'], // Extract the 'email' from the map.
      password: map['password'], // Extract the 'password' from the map.
      profileImagePath: map['profileImagePath'] ?? "", // Extract the 'profileImagePath' from the map, default to an empty string if null.
    );
  }

  // Method to convert the UserModel object back into a Map, which can be stored in databases like Firestore or SQLite.
  Map<String, dynamic> toMap() => {
    'id': id, // Include the 'id' field in the map.
    'name': name, // Include the 'name' field in the map.
    'phone': phone, // Include the 'phone' field in the map.
    'email': email, // Include the 'email' field in the map.
    'password': password, // Include the 'password' field in the map.
    'profileImagePath': profileImagePath, // Include the 'profileImagePath' field in the map.
  };
}
